name: Continuous Integration

on:
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.1.0

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Build plugin
        run: ./gradlew build --no-daemon --stacktrace

      - name: Run tests
        run: ./gradlew test --no-daemon --stacktrace

  verification:
    name: Marketplace verification
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.1.0

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Clean up Gradle cache
        run: ./gradlew clean --no-daemon --stacktrace

      - name: Verify plugin compatibility
        run: ./gradlew verifyPlugin --no-daemon --stacktrace

  lint:
    name: Codebase lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.1.0

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Run ktlint
        run: ./gradlew ktlintCheck --no-daemon --stacktrace
